version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: insightdigest_db
    restart: always
    environment:
      POSTGRES_USER: prem
      POSTGRES_PASSWORD: prem123
      POSTGRES_DB: insightdigest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
